### ISSUE TITLE
v1.10.0 Is not working

### ISSUE THREAD

**Issue by empowerVictor** [microsoft/SynapseVSCode#41]
The latest version simply doesn't work.

`Select Workspace` does nothing.

Both the top buttons on refresh and select workspace gives an error:
`command 'synapse.refresh' not found`
`command 'synapse.switchWorkspace' not found`

**Comment by johannzv** [comment]
Any update on this?

**Comment by tiang** [comment]
@realDuang: I'm also having issues with v1.10.0. I can switch to  v1.9.0 and log into Synapse and view my workspace.

I'm running on a Mac M2, Sonama 14.5, openJDK 23. 

The Extension host debug logs show this error:

```
2024-10-17 01:03:28.640 [info] ExtensionService#_doActivateExtension SynapseVSCode.synapse, startup: false, activationEvent: 'onCommand:synapse.switchWorkspace'
2024-10-17 01:03:28.739 [error] Activating extension SynapseVSCode.synapse failed due to an error:
2024-10-17 01:03:28.739 [error] Error: node-loader:
Error: dlopen(/Users/xxx/.vscode/extensions/synapsevscode.synapse-1.10.0/dist/extension/../bin/x64/dpapi.node, 0x0001): tried: '/Users/xxx/.vscode/extensions/synapsevscode.synapse-1.10.0/dist/extension/../bin/x64/dpapi.node' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Users/xxx/.vscode/extensions/synapsevscode.synapse-1.10.0/dist/extension/../bin/x64/dpapi.node' (no such file), '/Users/xxx/.vscode/extensions/synapsevscode.synapse-1.10.0/dist/extension/../bin/x64/dpapi.node' (not a mach-o file), '/Users/xxx/.vscode/extensions/synapsevscode.synapse-1.10.0/dist/bin/x64/dpapi.node' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Users/xxx/.vscode/extensions/synapsevscode.synapse-1.10.0/dist/bin/x64/dpapi.node' (no such file), '/Users/xxx/.vscode/extensions/synapsevscode.synapse-1.10.0/dist/bin/x64/dpapi.node' (not a mach-o file)
    at Object.22736 (/Users/xxx/.vscode/extensions/synapsevscode.synapse-1.10.0/dist/extension/extension.js:78175:9)
    at __webpack_require__ (/Users/xxx/.vscode/extensions/synapsevscode.synapse-1.10.0/dist/extension/extension.js:113169:42)
    at Object.14304 (/Users/xxx/.vscode/extensions/synapsevscode.synapse-1.10.0/dist/extension/extension.js:58009:14)
    at __webpack_require__ (/Users/xxx/.vscode/extensions/synapsevscode.synapse-1.10.0/dist/extension/extension.js:113169:42)
    at /Users/xxx/.vscode/extensions/synapsevscode.synapse-1.10.0/dist/extension/extension.js:185362:14
    at /Users/xxx/.vscode/extensions/synapsevscode.synapse-1.10.0/dist/extension/extension.js:188690:3
    at Object.<anonymous> (/Users/xxx/.vscode/extensions/synapsevscode.synapse-1.10.0/dist/extension/extension.js:188693:12)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at Function.c._load (node:electron/js2c/node_init:2:13801)
    at Function.e._load (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:10870)
    at Function.t._load (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:22422)
    at Function.i._load (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:4651)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at Module.require (/Users/xxx/.vscode/extensions/github.copilot-chat-0.21.2/dist/extension.js:206:34657)
    at require (node:internal/modules/helpers:179:18)
    at hB.xb (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:23767)
    at async Promise.all (index 0)

```

Searching for "not a mach-o file" shows this [link](https://github.com/getsentry/profiling-node/issues/192), which refers to cross compiling from x64 macos to arm64 for the newer macs.  

hope this helps, and please reach out if you need extra help troubleshooting this issue. it's a very useful extension, keep up the great work! <3

**Comment by jtcrd** [comment]
Pressing the `Select Workspace`  does nothing for me within the provided docker container. But also no logs.

**Comment by realDuang** [comment]
Sorry for the delay... and thanks for all your feedbacks.

This was due to the fact that we were following msal's security protocols, but it seemed to cause problems with Macs on the Arm architecture, which we've now fixed and released in the latest version.
